site: iwpnd
url: https://iwpnd.pw/
title: iwpnd
description: geographer turned data engineer turned backend developer

twitter:
  username: imwithpanda
  card: summary
author:
  twitter: imwithpanda
  name: iwpnd
  avatar: /img/iwpnd-logo.png
  email: ahoi@iwpnd.pw

permalink: pretty

google_analytics: UA-156087226-1

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /articles/:year-:month/:title

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
