
name: iwpnd
description: "geographer turned data something"
keywords: ["blog", "imwithpanda", "python", "data analysis", "data science", "data engineering"]

avatar: https://raw.githubusercontent.com/iwpnd/iwpnd.github.io/master/img/img.png
favicon: https://raw.githubusercontent.com/iwpnd/iwpnd.github.io/master/favicon.png

navigation:
  - name: home
    url: /
  - name: archive
    url: /archive
paginate: 4
excerpt_separator: <!-- more -->

footer-links: 
  weibo: 
  behance:
  dribbble: 
  email: ahoi@iwpnd.pw
  facebook:
  flickr: 
  github: iwpnd
  instagram: 
  linkedin: benjamin-ramser #https://www.linkedin.com/in/<>
  pinterest: 
  rss: 
  stackoverflow: 
  tumblr: 
  twitter: imwithpanda
  youtube: 

footer-text: Copyright (c) 2020 Benjamin Ramser

disqus: 


# github_comments_repository: iwpnd/iwpnd-blog-comments
google_analytics: UA-156087226-1

url: https://iwpnd.pw
baseurl: 
permalink: /articles/:year-:month/:title #/:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  parse_block_html: true

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-environment-variables

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

